# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - about.md
  - documentation.md

author:
 email: canoiaguiar@gmail.com
 username: canoi12
footer: 'follow on <a href="https://github.com/canoi12/">github</a>'

style: dark # dark (default) or light
# listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
